name: Checkout auto-minutes and npm install (use cache branch)

on:
  workflow_dispatch:
  push:
    branches:
      - main  

permissions:
  contents: read

jobs:
  setup-and-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js (lts)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Checkout ekr/auto-minutes into ./auto-minutes
        uses: actions/checkout@v4
        with:
          repository: ekr/auto-minutes
          path: auto-minutes
          fetch-depth: 0

      - name: What is the current git version
        working-directory: auto-minutes
        run: |
          git log -n 1

      - name: Install npm dependencies in auto-minutes
        working-directory: auto-minutes
        run: |
          npm ci

      - name: Checkout ietf-minutes/ietf-minutes-data (cache branch) inside auto-minutes
        uses: actions/checkout@v4
        with:
          repository: ietf-minutes/ietf-minutes-data
          ref: cache
          path: auto-minutes/cache
          fetch-depth: 0
          

      - name: Summarize the current meeting
        working-directory: auto-minutes
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node src/index.js -v --summarize 124 --source agenda

      - name: Generate the MD files
        working-directory: auto-minutes
        run: |
          node src/index.js -v --output

      - name: Build the site
        working-directory: auto-minutes
        run: |
          node src/index.js -v --build

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'auto-minutes/_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4